name: Unit tests
on: [ push, pull_request ]

env:
  GCC_VERSION: 13
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup CMake and Ninja
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      # Setup GCC
      - name: Setup compiler
        run: |
          sudo apt update
          sudo apt install -y gcc-${{env.GCC_VERSION}} g++-${{env.GCC_VERSION}}

      # Run CMake
      - name: Run CMake
        env:
          # Ensure that CMake uses the GCC version we want
          CC: gcc-${{env.GCC_VERSION}}
          CXX: g++-${{env.GCC_VERSION}}
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: 'CMakeLists.txt'
          configurePreset: 'release'
          buildPreset: 'release'
          testPreset: 'test-release'
